# This is a basic workflow to help you get started with Actions

name: Reorder

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    name: reorder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Update source code
        run: npm run reorder-confs
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Christian Grail
          author_email: cgrail@users.noreply.github.com
          message: 'Reorder conferences'
          add: '*.json'
